### ISSUE TITLE
Mező típus

### ISSUE THREAD

**Issue by Rittomi** [rittakos/RoomCreator#2]
Lehetne fordított sorrendben a pocsolya és a lyuk. Ha az se nehéz, akár a  jobb klikk is lehet a pocsolya.

**Comment by Rittomi** [comment]
Az lenne még jó, ha pocsolyából lenne 2 színű. Az egyik jó effektet adna, a másik rosszat. A jón és rosszon belul már random  lenne az effekt

**Comment by rittakos** [comment]
- [x] Lyuk, pocsolya fordtva
- [x] 2 pocsolya

**Comment by rittakos** [comment]
Világos kék a jó víz, sötét a rossz.
